29946 - Content model updates
XCentium/xcore.accelerator pull request #41
Opened 2023-10-18 13:24 UTC by AlexW301

#AB29946 - Updated kontent.ai content model and updated blog terminology to insights

2023-10-18 16:50 UTC, mhak requested changes

2023-10-18 16:50 UTC, mhak commented on contentstack-finserv/components/footer.tsx
> +  const [getFooter, setFooter] = useState(footer);
do we need states for the footer? I wouldn't expect it to be reactive

2023-10-18 16:52 UTC, AlexW301 commented on contentstack-finserv/components/footer.tsx
> +  const [getFooter, setFooter] = useState(footer);
I am not sure why that is in my pr, that footer is from the contentstack project. @zachary-horvath  ?

2023-10-18 16:59 UTC, zachary-horvath commented on contentstack-finserv/components/footer.tsx
> +  const [getFooter, setFooter] = useState(footer);
This is to be removed in the app router upgrade. State in the old app was used to update the data on the fly.

2023-10-19 16:17 UTC, zachary-horvath approved these changes
Approving this. File footer.tsx in contentstack-finserv/components does not exist in new app router branch.

2023-10-19 16:18 UTC, zachary-horvath commented
Approved. See above comments.

2023-10-19 16:18 UTC, merged