29612 - page title & metadata update
XCentium/xcore.accelerator pull request #52
Opened 2023-10-24 13:47 UTC by zachary-horvath

2023-10-24 15:34 UTC, mhak requested changes

2023-10-24 15:34 UTC, mhak commented on contentstack-finserv/app/experts/[slug]/page.tsx
> +        ? `${data?.seo?.meta_company} ${data?.seo?.meta_title}`
This should be called "Page Title Tag" field - conceivably they can add any text here, not just the company

2023-10-24 15:40 UTC, zachary-horvath commented on contentstack-finserv/app/experts/[slug]/page.tsx
> +        ? `${data?.seo?.meta_company} ${data?.seo?.meta_title}`
Do you think this is confusing with the meta title field? Typically, meta titles do contain the company/app name in some capacity.

2023-10-24 16:49 UTC, mhak requested changes

2023-10-24 16:49 UTC, mhak commented on contentstack-finserv/app/experts/[slug]/page.tsx
> +        ? `${data?.seo?.meta_company} ${data?.seo?.meta_title}`
feel free to come up with a better name, but it shouldn't just be "company", it should be any tag they want to add to the beginning or end of the page title

2023-10-24 19:27 UTC, mhak commented on contentstack-finserv/app/experts/[slug]/page.tsx
> +        ? `${data?.seo?.meta_company} ${data?.seo?.meta_title}`
right - it _usually_ shows the company name, but let's not limit it to that. Let's call it "Page Tag" to match the a/c and kontent.ai

2023-10-25 14:11 UTC, mhak approved these changes

2023-10-25 14:12 UTC, merged